### ISSUE TITLE
Better verification message format

### ISSUE THREAD

**Issue by roshanrags** [marlinprotocol/oyster-utility#11]
The current format is `attestation-verification-"0x1234"` for a public key of `0x1234`.

A better format is something like `abi.encodePacked("attestation-verification-", public_key)` in solidity. The public key is not hex encoded and its bytes are directly concatenated.

**Comment by WhiteWalker608** [comment]
https://github.com/marlinprotocol/oyster-attestation-utility/commit/5a5875bd69dda5bdf1a201e30d0abd8b4bf2c309
https://github.com/marlinprotocol/oyster-attestation-verifier/commit/29625b610811b349337569d11f2a2c9d8da638fb
