### ISSUE TITLE
Take secp256k1_public cli param instead of computing

### ISSUE THREAD

**Issue by roshanrags** [marlinprotocol/oyster-utility#4]

**Comment by roshanrags** [comment]
Seems like the private key is used only to derive the public key, once it is taken as cli param, private key can be removed.

**Comment by roshanrags** [comment]
And the secp256k1 dependency can be removed as well.

**Comment by WhiteWalker608** [comment]
https://github.com/marlinprotocol/oyster-attestation-utility/commit/4b4e6194113d2493b31121d0d261201b129557ca
